### ISSUE TITLE
Stability tracking - infrastructure

### ISSUE THREAD

**Issue by nrc** [nrc/dev-tools-team#15]
- [x] docs for managing out of tree tools (cargo, rls, ...)
- [x] rustup - auto-renaming of components (e.g., rls-beta -> rls)
- [x] ~~rustup - nightly only components~~ Not necessary if we are not going to keep tools on nightly
- [ ] rustup - dependent components (this would be nice, but doesn't need to block)

**Comment by nrc** [comment]
cc @brson, @alexcrichton

**Comment by nrc** [comment]
auto-renaming implemented in https://github.com/rust-lang-nursery/rustup.rs/pull/1237

**Comment by nrc** [comment]
This is done - the last remaining item is optional.

We do need a release of rustup though.
