### ISSUE TITLE
Stability tracking - RLS

### ISSUE THREAD

**Issue by nrc** [nrc/dev-tools-team#16]
To ride the trains:
- [x] tests are testing on Rust CI (https://github.com/rust-lang/rust/pull/42146)
- [x] rename (possibly automatically) rls component to rls-preview
- [x] De facto unstable features are behind the unstable features option
- [x] Unstable features option is linked to nightly toolchain
- [x] Decide on name of the Rustup component (proposed: rls-preview)
- [x] Proper channel info from `--version`.
- [x] Use the rls-rustc shim (https://github.com/rust-lang-nursery/rls/issues/435)

1.0:
- [ ] Quality - waiting on bug reports from stable channel release
- [ ] Cargo project coverage - lib + bin, workspaces
- [ ] Better testing (better protocol coverage, prevent regressions due to compiler data)
- [ ] new features - TBD

**Comment by nrc** [comment]
cc https://github.com/rust-lang/rust/pull/44141
