### ISSUE TITLE
Stability tracking - Rustfmt

### ISSUE THREAD

**Issue by nrc** [nrc/dev-tools-team#17]
Add to Rust product:
- [x] Add to Rust repo
- [ ] agree on stability criteria
- [x] tests running and passing on CI
- [x] overwrite mode by default
- [ ] implement stable/unstable command line arguments (unstable options are now supported, but we need to decide which options should be stable)
- [ ] resolve 'warnings for skipped sections'

1.0 - see https://github.com/rust-lang-nursery/rustfmt/issues/1860
