### ISSUE TITLE
Make it easier to contribute to tools

### ISSUE THREAD

**Issue by nrc** [nrc/dev-tools-team#5]
First concrete step is to have a webpage (linked from r-l.o) that lists tools and 'good first bugs' for each, plus contacts and some getting started advice.

**Comment by nrc** [comment]
See meeting discussion - https://github.com/nrc/dev-tools-team/blob/master/minutes/meeting%20notes%202017-06-12.md

**Comment by nrc** [comment]
https://github.com/nrc/dev-tools-team/tree/master/contribution

The following are concrete work items for the whole team:

- [x] checklist (https://github.com/nrc/dev-tools-team/blob/master/contribution/checklist.md)
- [ ] tools blog post (https://github.com/nrc/dev-tools-team/issues/14)
  - tell the tools story
- [ ] ongoing announcements - releases, status reports - low-level (specific issues) as well as high-level (roadmap), acknowledge contribution
- [ ] tools contribution page - link from r-l.o
- [ ] central tracking of good first issues (see https://starters.servo.org/)
- [ ] central documentation of how-to-contribute resources
  - in particular how to progress as a contributor
- [ ] contributor spreadsheet, integrate with GH

**Comment by fitzgen** [comment]
I [just](https://github.com/servo/rust-bindgen/pull/748) plugged some of the more obvious gaps from the checklist in `bindgen`'s `CONTRIBUTING.md` file. 

Would anyone like to do a general review of [our CONTRIBUTING.md file](https://github.com/fitzgen/rust-bindgen/blob/8fa5b81db0fabba8df571678ecdb8369e6622cbc/CONTRIBUTING.md) and contribution workflow? (probably outside of that PR).

Thanks!

**Comment by nrc** [comment]
Expanding on "central documentation of how-to-contribute resources ". Here are things I think we should have here and linked from all the tools:
- [ ] How to find something to work on
- [ ] where to look for docs, getting help (irc, don't be afraid to comment)
- [ ] Git and GitHub intro, including how to submit a PR, process for getting a review, merged, etc.
- [ ] How to make a good PR - e.g., have tests, docs (comments), communicate motivation, organised commits, commit messages, ....

What else should we have?

**Comment by fitzgen** [comment]
* maybe a summary of github issue labels' meanings?
